# Generated by Django 3.2.8 on 2021-11-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_proc', '0002_imgfacemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VdoFaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_face', models.FileField(upload_to='videoproc')),
            ],
        ),
        migrations.CreateModel(
            name='VdoProcModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videoproc')),
            ],
        ),
    ]
